"""empty message

Revision ID: acb80d05fde2
Revises: bdf89c30f2b2
Create Date: 2024-01-23 10:04:28.552766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acb80d05fde2"
down_revision = "bdf89c30f2b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(), nullable=False))
        batch_op.create_unique_constraint("uq_user_email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
